apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend-checkaction
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamwizard-backend-checkaction
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend-checkaction
    spec:
      containers:
        - name: streamwizard-backend-checkaction
          image: ghcr.io/streamerbuddybot/checkaction:c8b5dc0433729106ced2094beab65f0036026e16
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: streamwizard-backend
          volumeMounts:
            - name: grpc-dns
              mountPath: /usr/src/app/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: grpc-dns
          configMap:
            name: grpc-dns
