apiVersion: v1
kind: Service
metadata:
  name: streamwizard-backend-checkaction-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: streamwizard-backend-checkaction


